```{r, echo=FALSE}
# adjust and load as needed
source(file = "setup.R")
```

# GitHub and RStudio

## Objectives
:::objectives

* Link an RStudio project with GitHub
* Create and edit files in RStudio
* Commit and push changes to GitHub
:::

## Installation instructions

Please ensure that you have done the following before the course (needed for version control exercises):

1. Install R Studio, create a GitHub account and a GitHub Personal Access Token (copy latter as this is the only time it is displayed!) creation.
    a. Create a GitHub account on: [https://github.com](https://github.com)
    b. Make sure to have R Studio installed. You can download it [here](https://www.rstudio.com/products/rstudio/download/)
    c. Set up a personal token to allow R Studio to link to GitHub (this is in place of using a password): 
[https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token)

2. Install command line git software which will be used by R Studio:
    a. Installing command line git
[https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN](https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN)
    b. Later we will set up R Studio to access git and then it might be useful to know where git has been installed. This can be found out by either using the command `git --exec-path` from a command line prompt (Windows/Linux/Mac) or from the Terminal pane within R Studio.

On a Mac/Linux computer you can also issue a `which git` command at the command line or R Studio Terminal. Results may differ between these commands as operating systems often use aliases that point to the real location of the program.

## Key points

:::keypoints
Adding key points
:::
